// frontend/src/components/NewTodo.tsx
import React, { useRef, useContext } from 'react';
import styles from './styles/NewTodo.module.css';
import { TodosContext } from '../store/todos-context';
import axios from 'axios';
import { TodosContextModel } from './models/TodosContext';
import environment from '../environments/environment';

const NewTodo : React.FC = () =>
{
	const todosContext : TodosContextModel = useContext(TodosContext);
	const todoTextInputRef : React.MutableRefObject<HTMLInputElement> = useRef<HTMLInputElement>(null);

	async function sendTodo(title : string) : Promise<void>
	{
		await axios.post(environment.apiUrl + environment.apiRoutes.todos, { title });
	}

	function submitHandler(event : React.FormEvent)
	{
        event.preventDefault();
        const enteredText : string = todoTextInputRef.current.value;

        if (enteredText.trim().length !== 0)
        {
			todosContext.addTodo(enteredText);
			todoTextInputRef.current.value = '';
			sendTodo(enteredText);
        }
	}

	return (
		<form className={styles.form} onSubmit={submitHandler}>
			<label htmlFor="text">Todo text</label>
			<input type="text" id="text" ref={todoTextInputRef} data-test="text-input"/>
			<button data-test="add-button">Add Todo</button>
		</form>
	);
};

export default NewTodo;

// frontend/src/app/new-todo/new-todo.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../environments/environment';
import { Todo } from '../todo.model';

@Component({
  	selector: 'app-new-todo',
  	templateUrl: './new-todo.component.html',
  	styleUrls: [ './new-todo.component.css' ]
})
export class NewTodoComponent implements OnInit
{
	todo : Todo = { title:'', _id:'' };

	constructor(private http : HttpClient)
	{ }

	ngOnInit() : void
	{
	}

	addNewTodo() : void
	{
		this.http.post(environment.apiUrl + environment.apiRoutes.todos, this.todo)
			.subscribe(todo => ({ message:todo }));
		this.todo.title = '';
	}
}

<form class="form-container">
	<label class="form-text-input">
		<input type="text" [(ngModel)]="todo.title" data-test="text-input"/>
	</label>
	<button (click)="addNewTodo()" data-test="add-button">Add Todo</button>
</form>
